INSERT INTO TIPO VALUES (101, 'Samsung', 'el mejor');
INSERT INTO TIPO VALUES (102, 'Tablet', 'buen rendimiento');


INSERT INTO DISPOSITIVO VALUES (1, 'S3', 101, 'primero', 0);
INSERT INTO DISPOSITIVO VALUES (2, 'S6', 101, 'del 2016', 0);
INSERT INTO DISPOSITIVO VALUES (3, 'S8', 101, 'del 2018', 0);
INSERT INTO DISPOSITIVO VALUES (4, 'S9 Plus', 101, 'ultima generación', 0);
INSERT INTO DISPOSITIVO VALUES (5, 'N100', 102, 'modelo básico', 0);
INSERT INTO DISPOSITIVO VALUES (6, 'N700', 102, 'comodidad y almacenaje amplio', 0);

/*
INSERT INTO DISPOSITIVO (DISPOSITIVO_ID, DISPOSITIVO, TIPO_ID, DESCRIPTION, SKU) VALUES (1, 'S3', 101, "primero", 0);
INSERT INTO DISPOSITIVO (DISPOSITIVO_ID, DISPOSITIVO, TIPO_ID, DESCRIPTION, SKU) VALUES (2, 'S6', 101, "del 2016", 0);
INSERT INTO DISPOSITIVO (DISPOSITIVO_ID, DISPOSITIVO, TIPO_ID, DESCRIPTION, SKU) VALUES (3, 'S8', 101, "del 2018", 0);
INSERT INTO DISPOSITIVO (DISPOSITIVO_ID, DISPOSITIVO, TIPO_ID, DESCRIPTION, SKU) VALUES (4, 'S9 Plus', 101, "ultima generación", 0);
INSERT INTO DISPOSITIVO (DISPOSITIVO_ID, DISPOSITIVO, TIPO_ID, DESCRIPTION, SKU) VALUES (5, 'N100', 102, "modelo básico", 0);
INSERT INTO DISPOSITIVO (DISPOSITIVO_ID, DISPOSITIVO, TIPO_ID, DESCRIPTION, SKU) VALUES (6, 'N700', 102, "comodidad y almacenaje amplio", 0);
*/